apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-files
binaryData:
{{ range $path, $bytes := .Files.Glob (printf "config/***")}}
{{ $name := base $path }}
{{- sha256sum (printf "%s/%s" (index (regexSplit "config" (dir $path) -1) 1 ) $name ) | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
{{ end }}
