---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu.name" . }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.p2p.port }}
      targetPort: discovery
      protocol: UDP