
logging="{{- logLevel}}"
data-path="/opt/besu/data"
host-whitelist=["*"]

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# graphql
graphql-http-enabled=true
graphql-http-host="0.0.0.0"
graphql-http-port=8547
graphql-http-cors-origins=["*"]

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# permissions
{% if enableNodePermissions %}
permissions-nodes-config-file-enabled=true
permissions-nodes-config-file="/config/permissions_config.toml"
{% else %}
permissions-nodes-config-file-enabled=false
{% endif %}

{% if enableBootNodes %}
# bootnodes
bootnodes=[
{%- for node in nodeConfig | byAttr('boot', true) -%}
{%- if enableDNS -%}
"enode://{{- node.publicKey}}@{{- node.name}}:30303"{{- "," if not loop.last}}
{%- else -%}
"enode://{{- node.publicKey}}@{{- node.ip}}:30303"{{- "," if not loop.last}}
{%- endif -%}
{%- endfor -%}]
{% endif %}

{% if enableStaticNodes %}
# static nodes
static-nodes-file="/config/static-nodes.json"
{% endif %}

# p2p discovery
{% if enableP2PDiscovery %}
discovery-enabled=true
{% else %}
discovery-enabled=false
{% endif %}


{% if enableDNS %}
# dns
Xdns-enabled=true
Xdns-update-enabled=true
{% endif %}

min-gas-price={{- minGasPrice}}
{% if enableMiner %}
miner-enabled=true
miner-coinbase="0x{{- minerCoinbase}}"
{% endif %}